# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9714c46d1517247e8c05ba5f869af3ab9f4e71894416e1a9528e420ade1f363c8722e73eb2b9cebb03776baa0ccebd5cc65e7693d5514490f0981f25a390f01

test:
  secret_key_base: 6d15dce08a0e99dc131e15d5cc2171d32ea41923537363e2130315f48947e10a03a1012f527e5f5a84307a7bb0f698f18d3133fdccfe7d9b5d39cf3b553b9260

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
